In [1]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.02501467 -0.00128168 -0.01623744 -0.0133359 ]
[ 0.02498903 -0.19616704 -0.01650415  0.27418002]
[ 0.02106569 -0.00081355 -0.01102055 -0.02366232]
[ 0.02104942  0.1944647  -0.0114938  -0.31980189]
[ 0.02493871 -0.00049169 -0.01788984 -0.03076572]
[ 0.02492888  0.19488218 -0.01850515 -0.32903896]
[ 0.02882652  0.39026262 -0.02508593 -0.62749964]
[ 0.03663178  0.58572555 -0.03763592 -0.92797628]
[ 0.04834629  0.78133487 -0.05619545 -1.23224483]
[ 0.06397299  0.97713265 -0.08084035 -1.54199066]
[ 0.08351564  1.17312809 -0.11168016 -1.85876487]
[ 0.1069782   1.36928447 -0.14885546 -2.1839322 ]
[ 0.13436389  1.17588708 -0.1925341  -1.9406462 ]
Episode finished after 13 timesteps
[-0.00140359 -0.00108881 -0.04490176 -0.00656478]
[-0.00142537  0.19464738 -0.04503305 -0.31306981]
[ 0.00246758  0.00019492 -0.05129445 -0.03492208]
[ 0.00247148 -0.19415536 -0.05199289  0.24114595]
[-0.00141163 -0